import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/components/AuthProvider";
import localFont from 'next/font/local';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const WorkSans = localFont({
  src: [
    {
      path: '/fonts/WorkSans-Black.ttf', // Path to your font file in the public folder
      weight: '900', // Regular weight
      style: 'normal', // Normal style
    },
    {
      path: '/fonts/WorkSans-ExtraBold.ttf', // Path to your font file in the public folder
      weight: '800', // Regular weight
      style: 'normal', // Normal style
    },
    {
      path: '/fonts/WorkSans-Bold.ttf', // Path to your font file in the public folder
      weight: '700', // Regular weight
      style: 'normal', // Normal style
    },
    {
      path: '/fonts/WorkSans-SemiBold.ttf', // Path to your font file in the public folder
      weight: '600', // Regular weight
      style: 'normal', // Normal style
    },
    {
      path: '/fonts/WorkSans-Medium.ttf', // Path to your font file in the public folder
      weight: '500', // Regular weight
      style: 'normal', // Normal style
    },
    {
      path: '/fonts/WorkSans-Regular.ttf', // Path to your font file in the public folder
      weight: '400', // Regular weight
      style: 'normal', // Normal style
    },
    {
      path: '/fonts/WorkSans-Thin.ttf', // Path to your font file in the public folder
      weight: '300', // Regular weight
      style: 'normal', // Normal style
    },
    {
      path: '/fonts/WorkSans-Light.ttf', // Path to your font file in the public folder
      weight: '200', // Regular weight
      style: 'normal', // Normal style
    },
    {
      path: '/fonts/WorkSans-ExtraLight.ttf', // Path to your font file in the public folder
      weight: '100', // Regular weight
      style: 'normal', // Normal style
    },
  ],
  // display: 'swap', // Optional: control font display strategy
  variable: '--font-work-sans'
});


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={WorkSans.variable}>
        {/* Wrap everything with SessionProvider */}
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
